# Generated by Django 5.2.12 on 2026-03-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='name')),
                ('description', models.TextField(max_length=300, verbose_name='descrition')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('available', models.BooleanField(default=True, verbose_name='avalilable')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='photo')),
            ],
        ),
    ]
